# Generated by Django 5.2.8 on 2025-11-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
